#!/bin/bash
cd ~
git clone https://github.com/team7tomat/raspi.git

cd ~/raspi/pigpiod-master && make && make install # install pigpiod

cd ~/raspi
cp -f .bashrc ~/.bashrc # replace bashrc

sudo apt-get install python3
sudo apt-get install python3-pip
pip3 install -r requirements.txt

sudo reboot
